spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

logging:
  level:
    com.schoolmanagement.usermng: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: devSecretKeyForJWTTokenGenerationInDevelopmentEnvironment
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days
